/**
 * FRAME AGENCY - SECURITY VERIFICATION MODULE (2FA)
 * Version: 2.5 (High Fidelity)
 * Author: Generated by Gemini 3 Pro
 * * Instructions: Inject this script at the end of the <body> tag.
 * No external CSS required. All styles are injected dynamically.
 */

(function() {
    'use strict';

    // ============================================================================
    // 1. CONFIGURAÇÃO E CONSTANTES
    // ============================================================================
    const CONFIG = {
        mockCode: '12345',
        timerDuration: 300, // 5 minutos em segundos
        emailExpiry: 7200000, // 2 horas em ms
        maxAttempts: 3,
        blockDuration: 86400000, // 24 horas em ms
        assets: {
            emailIcon: 'https://framerusercontent.com/images/sz5ueC0VcN5fohNrik0bUG9oJbI.png',
            lottieMain: 'https://lottie.host/27108e59-5743-41a0-980f-c45cc774f50e/qT7a4kmpdD.lottie',
            lottieResend: 'https://lottie.host/a11872ae-9848-45ba-8871-fa870929372e/YWZlUTBnMU.lottie'
        },
        colors: {
            primary: '#AC865C',     // Marrom Frame
            primaryDark: '#8b6d4d',
            bg: '#FFFFFF',
            text: '#1F1F1F',
            subtle: '#F5F5F5',
            border: '#E0E0E0',
            error: '#e74c3c'
        }
    };

    const STORAGE_KEY = 'frame_auth_v2_state';

    // Estado inicial padrão
    let state = {
        email: null,
        emailTimestamp: null,
        attempts: 0,
        resends: 0,
        timerEnd: null,
        isBlocked: false,
        blockUntil: null
    };

    // ============================================================================
    // 2. GESTÃO DE ESTADO (LOCALSTORAGE)
    // ============================================================================
    function loadState() {
        const saved = localStorage.getItem(STORAGE_KEY);
        if (saved) {
            const parsed = JSON.parse(saved);
            state = { ...state, ...parsed };
            
            // Verificar expiração do e-mail
            if (state.email && (Date.now() - state.emailTimestamp > CONFIG.emailExpiry)) {
                state.email = null; // Resetar e-mail se expirou
            }
        }
    }

    function saveState() {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    }

    function checkBlockStatus() {
        if (state.isBlocked && state.blockUntil) {
            if (Date.now() < state.blockUntil) {
                return true;
            } else {
                // Desbloquear se o tempo passou
                state.isBlocked = false;
                state.blockUntil = null;
                state.attempts = 0;
                state.resends = 0;
                saveState();
            }
        }
        return false;
    }

    function triggerBlock() {
        state.isBlocked = true;
        state.blockUntil = Date.now() + CONFIG.blockDuration;
        saveState();
        renderBlockInterface();
    }

    // ============================================================================
    // 3. ESTILOS CSS (INJETADOS)
    // ============================================================================
    function injectStyles() {
        const styleId = 'frame-auth-styles';
        if (document.getElementById(styleId)) return;

        const css = `
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

            :root {
                --f-primary: ${CONFIG.colors.primary};
                --f-primary-dark: ${CONFIG.colors.primaryDark};
                --f-bg: ${CONFIG.colors.bg};
                --f-text: ${CONFIG.colors.text};
                --f-border: ${CONFIG.colors.border};
            }

            /* Container Geral */
            #frame-auth-root {
                font-family: 'Inter', system-ui, -apple-system, sans-serif;
                position: fixed;
                top: 0; left: 0; width: 100%; height: 100%;
                background: rgba(255, 255, 255, 0.98);
                z-index: 9999;
                display: flex;
                align-items: center;
                justify-content: center;
                overflow-y: auto;
            }

            /* Glass Card */
            .frame-card {
                width: 100%;
                max-width: 440px;
                background: white;
                border-radius: 24px;
                padding: 40px 32px;
                box-shadow: 0 10px 40px rgba(0,0,0,0.06), 0 1px 3px rgba(0,0,0,0.04);
                border: 1px solid rgba(172, 134, 92, 0.2);
                text-align: center;
                position: relative;
                animation: frameSlideUp 0.5s cubic-bezier(0.16, 1, 0.3, 1);
            }

            /* Email Identifier */
            .email-pill {
                display: inline-flex;
                align-items: center;
                background: #F8F9FA;
                padding: 6px 16px 6px 6px;
                border-radius: 50px;
                border: 1px solid #EEEEEE;
                margin: 20px 0;
                max-width: 100%;
            }
            .email-pill img {
                width: 32px; height: 32px; border-radius: 50%;
                margin-right: 10px; object-fit: cover;
            }
            .email-pill span {
                font-size: 14px; color: #555; font-weight: 500;
                white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
            }

            /* Inputs 2FA */
            .code-container {
                display: flex;
                gap: 10px;
                justify-content: center;
                margin: 24px 0;
            }
            .code-input {
                width: 52px; height: 64px;
                border: 1px solid #DDD;
                border-radius: 12px;
                font-size: 24px; font-weight: 600;
                text-align: center; color: var(--f-text);
                transition: all 0.2s ease;
                background: #fff;
                outline: none;
            }
            .code-input:focus {
                border-color: var(--f-primary);
                box-shadow: 0 0 0 3px rgba(172, 134, 92, 0.2);
                transform: translateY(-2px);
            }
            
            /* Shake Animation */
            .shake { animation: shake 0.4s cubic-bezier(.36,.07,.19,.97) both; border-color: #e74c3c !important; color: #e74c3c; }

            /* Timer & Resend */
            .timer-text { font-size: 14px; color: #888; margin-bottom: 8px; font-variant-numeric: tabular-nums; }
            .resend-link { 
                color: var(--f-primary); font-weight: 600; font-size: 14px; 
                text-decoration: none; cursor: pointer; opacity: 1; transition: opacity 0.2s;
            }
            .resend-link.disabled { opacity: 0.5; cursor: not-allowed; pointer-events: none; }

            /* Email Modal Specifics */
            .email-input-group { position: relative; margin-top: 24px; text-align: left; }
            .email-input {
                width: 100%; padding: 16px; border-radius: 12px;
                border: 1px solid #CCC; font-size: 16px;
                transition: 0.2s; outline: none; box-sizing: border-box;
            }
            .email-input:focus { border-color: var(--f-primary); box-shadow: 0 0 0 3px rgba(172, 134, 92, 0.1); }
            .action-btn {
                width: 100%; margin-top: 16px; padding: 16px;
                background: var(--f-primary); color: white;
                border: none; border-radius: 12px; font-weight: 600; font-size: 16px;
                cursor: pointer; transition: background 0.2s;
            }
            .action-btn:hover { background: var(--f-primary-dark); }
            .action-btn:disabled { background: #CCC; cursor: not-allowed; }

            /* Footer Disclaimer */
            .auth-footer {
                margin-top: 32px; padding-top: 16px;
                border-top: 1px solid #ECEFF1;
                font-size: 11px; color: #999;
                display: flex; justify-content: space-between;
            }
            .auth-footer a { color: #999; text-decoration: none; }

            /* Lottie Sizing */
            dotlottie-player { width: 120px; height: 120px; margin: 0 auto; }

            /* Animations */
            @keyframes frameSlideUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
            @keyframes shake { 10%, 90% { transform: translate3d(-1px, 0, 0); } 20%, 80% { transform: translate3d(2px, 0, 0); } 30%, 50%, 70% { transform: translate3d(-4px, 0, 0); } 40%, 60% { transform: translate3d(4px, 0, 0); } }
            
            /* Responsive */
            @media (max-width: 480px) {
                .frame-card { border-radius: 0; height: 100vh; max-width: 100%; border: none; padding-top: 60px; }
                .code-input { width: 42px; height: 52px; font-size: 20px; }
            }

            /* --- BLOCK & TOAST STYLES (From Prompt) --- */
            .f-toast {
                position: fixed; top: 20px; right: 20px; width: 400px;
                background: white; border-radius: 16px; box-shadow: 0 20px 40px rgba(0,0,0,0.15);
                padding: 18px; display: flex; gap: 14px; z-index: 10001;
                border: 1px solid #eee; animation: slideDown 0.65s cubic-bezier(0.22, 1, 0.36, 1) forwards;
            }
            .f-modal-backdrop {
                position: fixed; inset: 0; background: rgba(0,0,0,0.04); backdrop-filter: blur(2px);
                z-index: 10000; display: flex; justify-content: center; align-items: center;
                animation: fadeIn 0.3s ease;
            }
            .f-modal {
                background: white; width: 90%; max-width: 420px; border-radius: 20px;
                padding: 32px 24px; text-align: center; box-shadow: 0 25px 60px rgba(0,0,0,0.3);
                animation: zoomIn 0.3s ease; position: relative;
            }
            .code-display { font-size: 28px; font-weight: 700; color: var(--f-primary); letter-spacing: 2px; margin: 16px 0; }
            @keyframes slideDown { from { transform: translateY(-40px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
            @keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }
            @keyframes zoomIn { from { transform: scale(0.9); opacity: 0; } to { transform: scale(1); opacity: 1; } }
        `;

        const style = document.createElement('style');
        style.id = styleId;
        style.textContent = css;
        document.head.appendChild(style);
    }

    // ============================================================================
    // 4. DEPENDÊNCIAS (LOTTIE)
    // ============================================================================
    function loadLottieScript() {
        if (!document.querySelector('script[src*="dotlottie-player"]')) {
            const script = document.createElement('script');
            script.type = 'module';
            script.src = 'https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs';
            document.head.appendChild(script);
        }
    }

    // ============================================================================
    // 5. INTERFACES (DOM BUILDER)
    // ============================================================================
    
    // --- Container Raiz ---
    function getOrCreateRoot() {
        let root = document.getElementById('frame-auth-root');
        if (!root) {
            root = document.createElement('div');
            root.id = 'frame-auth-root';
            document.body.appendChild(root);
        }
        root.innerHTML = ''; // Limpar conteúdo anterior
        return root;
    }

    // --- Modal de E-mail (Passo 1) ---
    function renderEmailInterface() {
        const root = getOrCreateRoot();
        
        const container = document.createElement('div');
        container.className = 'frame-card';
        
        container.innerHTML = `
            <dotlottie-player src="${CONFIG.assets.lottieMain}" background="transparent" speed="1" direction="1" playMode="normal" loop autoplay></dotlottie-player>
            <h2 style="font-size: 22px; margin: 10px 0 5px;">Identificação</h2>
            <p style="color: #666; font-size: 14px;">Digite seu e-mail para receber o código de acesso.</p>
            
            <form id="frame-email-form">
                <div class="email-input-group">
                    <input type="email" id="f-email" class="email-input" placeholder="nome@email.com" required autocomplete="email">
                </div>
                <button type="submit" class="action-btn" id="f-email-btn" disabled>Continuar</button>
            </form>
            
            <div class="auth-footer">
                <span>© 2026 Frame Agency</span>
                <a href="#">Privacidade & Termos</a>
            </div>
        `;

        root.appendChild(container);

        // Lógica do Modal de E-mail
        const input = document.getElementById('f-email');
        const btn = document.getElementById('f-email-btn');

        input.focus();

        input.addEventListener('input', (e) => {
            const isValid = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e.target.value);
            btn.disabled = !isValid;
        });

        document.getElementById('frame-email-form').addEventListener('submit', (e) => {
            e.preventDefault();
            if (btn.disabled) return;

            // Salvar estado
            state.email = input.value;
            state.emailTimestamp = Date.now();
            
            // Iniciar Timer se não existir
            if (!state.timerEnd) {
                state.timerEnd = Date.now() + (CONFIG.timerDuration * 1000);
            }
            
            saveState();
            
            // Transição visual
            container.style.opacity = '0';
            container.style.transform = 'translateY(-20px)';
            container.style.transition = 'all 0.3s ease';
            
            setTimeout(() => {
                render2FAInterface();
                showToast(`Código enviado para ${state.email}`);
            }, 300);
        });
    }

    // --- Interface de Código 2FA (Passo 2) ---
    function render2FAInterface() {
        const root = getOrCreateRoot();

        // Verificar se usuário já existe
        if (state.email && document.visibilityState === 'visible') {
            // Toast de boas-vindas ao recarregar
            // showToast("Salvamos seu e-mail, prossiga agora.");
        }

        const container = document.createElement('div');
        container.className = 'frame-card';

        container.innerHTML = `
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px;">
                 <h2 style="font-size: 22px; margin:0; text-align:left;">Verificação de<br>Segurança</h2>
                 <div style="width:50px; height:50px;">
                    <dotlottie-player src="${CONFIG.assets.lottieMain}" background="transparent" speed="1" loop autoplay></dotlottie-player>
                 </div>
            </div>
            
            <div class="email-pill">
                <img src="${CONFIG.assets.emailIcon}" alt="Globe">
                <span>${state.email}</span>
            </div>

            <p style="color: #666; font-size: 14px; margin-bottom: 20px;">
                Insira o código de 5 dígitos enviado para o seu e-mail.
            </p>

            <div class="code-container" id="otp-container">
                <input type="tel" maxlength="1" class="code-input" data-idx="0">
                <input type="tel" maxlength="1" class="code-input" data-idx="1">
                <input type="tel" maxlength="1" class="code-input" data-idx="2">
                <input type="tel" maxlength="1" class="code-input" data-idx="3">
                <input type="tel" maxlength="1" class="code-input" data-idx="4">
            </div>

            <div id="timer-display" class="timer-text">05:00</div>
            <a id="resend-btn" class="resend-link">Reenviar código</a>

            <div class="auth-footer">
                <span>Protegido por Frame Authentic™</span>
                <a href="https://frameag.com" target="_blank">Ajuda</a>
            </div>
        `;

        root.appendChild(container);

        setupOTPLogic();
        startTimer();
        
        // Auto-focus no primeiro
        setTimeout(() => document.querySelector('.code-input').focus(), 100);

        // Lógica de Reenvio
        document.getElementById('resend-btn').addEventListener('click', handleResend);
    }

    // ============================================================================
    // 6. LÓGICA DO 2FA (INPUTS & VALIDAÇÃO)
    // ============================================================================
    function setupOTPLogic() {
        const inputs = document.querySelectorAll('.code-input');
        
        inputs.forEach((input, index) => {
            // Apenas números
            input.addEventListener('input', (e) => {
                e.target.value = e.target.value.replace(/[^0-9]/g, '');
                if (e.target.value) {
                    if (index < inputs.length - 1) inputs[index + 1].focus();
                    checkCompletion();
                }
            });

            // Backspace e Navegação
            input.addEventListener('keydown', (e) => {
                if (e.key === 'Backspace' && !e.target.value && index > 0) {
                    inputs[index - 1].focus();
                }
            });

            // Smart Paste
            input.addEventListener('paste', (e) => {
                e.preventDefault();
                const pasteData = (e.clipboardData || window.clipboardData).getData('text');
                const cleanData = pasteData.replace(/[^0-9]/g, '').slice(0, 5);
                
                if (cleanData) {
                    cleanData.split('').forEach((char, i) => {
                        if (inputs[i]) inputs[i].value = char;
                    });
                    // Focar no próximo vazio ou no último
                    const lastFilled = Math.min(cleanData.length, 4);
                    inputs[lastFilled].focus();
                    checkCompletion();
                }
            });
        });
    }

    function checkCompletion() {
        const inputs = document.querySelectorAll('.code-input');
        const code = Array.from(inputs).map(i => i.value).join('');

        if (code.length === 5) {
            validateCode(code);
        }
    }

    function validateCode(code) {
        const inputs = document.querySelectorAll('.code-input');
        
        if (code === CONFIG.mockCode) {
            // SUCESSO
            inputs.forEach(i => {
                i.style.borderColor = '#27ae60';
                i.style.color = '#27ae60';
                i.disabled = true;
            });
            showToast("Verificação concluída com sucesso!");
            setTimeout(() => {
                // Aqui redirecionaria ou fecharia
                document.getElementById('frame-auth-root').innerHTML = '<div style="color:#AC865C; font-size:24px; font-weight:bold;">Acesso Permitido</div>';
            }, 1000);
            
            // Limpar estado após sucesso
            localStorage.removeItem(STORAGE_KEY);
        } else {
            // ERRO
            handleErrorAttempt(inputs);
        }
    }

    function handleErrorAttempt(inputs) {
        // Animação de erro
        inputs.forEach(i => {
            i.classList.add('shake');
            i.value = '';
        });

        state.attempts += 1;
        saveState();

        setTimeout(() => {
            inputs.forEach(i => i.classList.remove('shake'));
            inputs[0].focus();
        }, 500);

        if (state.attempts >= CONFIG.maxAttempts) {
            triggerBlock();
        }
    }

    function handleResend() {
        const btn = document.getElementById('resend-btn');
        if (btn.classList.contains('disabled')) return;

        state.resends += 1;
        
        if (state.resends >= CONFIG.maxAttempts) {
            triggerBlock();
            return;
        }

        saveState();
        
        // Simular envio
        btn.innerHTML = 'Enviando...';
        btn.classList.add('disabled');
        
        // Modal Lottie temporário
        const modal = document.createElement('div');
        modal.style.cssText = 'position:fixed; top:50%; left:50%; transform:translate(-50%,-50%); background:white; padding:20px; border-radius:16px; box-shadow:0 10px 30px rgba(0,0,0,0.2); z-index:10002; text-align:center;';
        modal.innerHTML = `<dotlottie-player src="${CONFIG.assets.lottieResend}" background="transparent" speed="1" loop autoplay style="width:100px;height:100px;"></dotlottie-player><p>Reenviando...</p>`;
        document.body.appendChild(modal);

        setTimeout(() => {
            modal.remove();
            btn.innerHTML = 'Código reenviado!';
            setTimeout(() => {
                btn.innerHTML = 'Reenviar código';
                btn.classList.remove('disabled');
            }, 2000);
            // Reset timer logic could go here if needed
        }, 2000);
    }

    // ============================================================================
    // 7. TIMER E UTILITÁRIOS
    // ============================================================================
    function startTimer() {
        const display = document.getElementById('timer-display');
        const resendBtn = document.getElementById('resend-btn');
        
        const interval = setInterval(() => {
            const now = Date.now();
            const remaining = Math.max(0, Math.ceil((state.timerEnd - now) / 1000));
            
            const minutes = Math.floor(remaining / 60).toString().padStart(2, '0');
            const seconds = (remaining % 60).toString().padStart(2, '0');
            
            if (display) display.textContent = `${minutes}:${seconds}`;

            if (remaining <= 0) {
                clearInterval(interval);
                disableInterface();
            }
        }, 1000);
    }

    function disableInterface() {
        const inputs = document.querySelectorAll('.code-input');
        inputs.forEach(i => i.disabled = true);
        
        const modal = document.createElement('div');
        modal.className = 'f-modal-backdrop';
        modal.innerHTML = `
            <div class="f-modal">
                <h2>Tempo Expirado</h2>
                <p style="color:#666;">Por segurança, sua sessão expirou.</p>
                <button class="action-btn" onclick="location.reload()">Reiniciar</button>
            </div>
        `;
        document.body.appendChild(modal);
    }

    function showToast(msg) {
        const toast = document.createElement('div');
        toast.className = 'f-toast';
        toast.style.width = 'auto';
        toast.style.maxWidth = '300px';
        toast.style.padding = '12px 20px';
        toast.innerHTML = `<span style="font-weight:500; font-size:14px; color:#1F1F1F;">${msg}</span>`;
        document.body.appendChild(toast);
        setTimeout(() => {
            toast.style.opacity = '0';
            setTimeout(() => toast.remove(), 500);
        }, 4000);
    }

    // ============================================================================
    // 8. SISTEMA DE BLOQUEIO (MODAL ROBUSTO)
    // ============================================================================
    function renderBlockInterface() {
        const root = getOrCreateRoot();
        root.innerHTML = ''; // Limpar tudo
        root.style.background = 'rgba(255,255,255,0.8)';
        root.style.backdropFilter = 'blur(5px)';

        // 1. Toast de Erro (Topo)
        const errorToast = document.createElement('div');
        errorToast.className = 'f-toast';
        errorToast.innerHTML = `
            <div style="color:#e74c3c;">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="9" r="1"/><path d="M12 12v4"/><path d="M9 16h6"/></svg>
            </div>
            <div>
                <strong style="display:block; margin-bottom:4px; font-size:16px;">Não foi possível validar</strong>
                <p style="margin:0; font-size:13px; color:#666; line-height:1.4;">Atividade incomum detectada. Proteção temporária aplicada.</p>
                <button id="btn-reason" style="background:none; border:none; color:${CONFIG.colors.primary}; text-decoration:underline; font-weight:600; font-size:13px; padding:0; margin-top:8px; cursor:pointer;">Entenda o motivo</button>
            </div>
        `;
        root.appendChild(errorToast);

        // Evento do botão "Entenda o motivo"
        document.getElementById('btn-reason').addEventListener('click', () => {
            const modalBackdrop = document.createElement('div');
            modalBackdrop.className = 'f-modal-backdrop';
            modalBackdrop.innerHTML = `
                <div class="f-modal">
                    <button class="close-modal" style="position:absolute; top:15px; right:15px; border:none; background:none; font-size:18px; cursor:pointer;">✕</button>
                    <div style="color:${CONFIG.colors.primary}; margin-bottom:15px;">
                        <svg width="50" height="50" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="8" r="1.5"/><path d="M10.5 12h3l-1.5 5"/></svg>
                    </div>
                    <h2 style="font-size:20px; margin-bottom:10px;">Por que isso aconteceu?</h2>
                    <p style="color:#666; font-size:14px; line-height:1.6;">A <strong>Tecnologia da Frame</strong> identificou tentativas de acesso inválidas consecutivas.</p>
                    <div style="background:#F9F9F9; padding:15px; border-radius:12px; margin:20px 0;">
                        <p style="font-size:12px; color:#999; margin-bottom:5px;">CÓDIGO DE ERRO</p>
                        <div class="code-display">F-39021</div>
                        <p style="font-size:12px; color:#e74c3c;">Bloqueio temporário de 24h</p>
                    </div>
                    <a href="https://t.me/suporteframebot?start=restriction-security-signup" target="_blank" class="action-btn" style="text-decoration:none; display:inline-block; line-height:1.2;">Falar com suporte</a>
                </div>
            `;
            root.appendChild(modalBackdrop);
            
            modalBackdrop.querySelector('.close-modal').onclick = () => modalBackdrop.remove();
        });
    }

    // ============================================================================
    // 9. INICIALIZAÇÃO
    // ============================================================================
    function init() {
        loadState();
        injectStyles();
        loadLottieScript();

        // Verificar bloqueio imediato
        if (checkBlockStatus()) {
            triggerBlock();
            return;
        }

        // Roteamento de Estado
        if (state.email && !state.isBlocked) {
            render2FAInterface();
        } else {
            renderEmailInterface();
        }
    }

    // Executar
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }

})();